version: "3"

services:
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: "npm start"
    ports:
      - "${FRONTEND_APP_PORT}:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0 --port=80"
    ports:
      - "${BACKEND_APP_PORT}:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql-db-data:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql

volumes:
  mysql-db-data:
